version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - npm install --silent --no-progress -g serverless
  build:
    commands:
      - serverless deploy --stage $ENVIROMENT --region $REGION --conceal --verbose